#!/usr/bin/env ruby

require_relative "./lib/keybase"

git_tags = `git tag`.split("\n")

if git_tags.include?(Keybase::VERSION)
  puts "Did you forget to update Keybase::VERSION?"
  exit
end

system "git tag #{Keybase::VERSION}"
system "git push origin #{Keybase::VERSION}"
system "gem build keybase-unofficial"
system "gem push keybase-unofficial-#{Keybase::VERSION}.gem"

File.delete("keybase-unofficial-#{Keybase::VERSION}.gem")
